name: Deploy image
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled, ready_for_review]
  repository_dispatch:
  push:
    branches:
      - develop
      - '[vt][0-9].[0-9]+.[0-9x]+*'
    tags:
      - "*"
env:
  DHUBU: ${{secrets.DHUBU}}
  DHUBP: ${{secrets.DHUBP}}
  BUILD_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-neon-faucet:
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DHUBU }}
          password: ${{ secrets.DHUBP }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: build docker image
        run: |
          docker build -f Dockerfile . --tag=neonlabsorg/faucet:${GITHUB_SHA}

      - name: publish image
        run: |
          docker push neonlabsorg/faucet:${GITHUB_SHA}
          docker tag neonlabsorg/faucet:${GITHUB_SHA} neonlabsorg/faucet:${ GITHUB_REF_NAME }
          docker push neonlabsorg/faucet:${ GITHUB_REF_NAME }
